version: '3.8'

services:
  safer-dreamcord:
    image: shimaenaga1123/safer-dreamcord:latest
    container_name: safer-dreamcord
    ports:
      - "8080:8080"
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    restart: unless-stopped
